### ISSUE TITLE
If a clone is deleted while it still has a sequence running, it will throw a nullPointerException

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#110]
java.lang.NullPointerException
    at Scratch$CloneStartSeq.isTriggered(Scratch.java:484)
    at Scratch.act(Scratch.java:983)
    at greenfoot.core.Simulation.actActor(Simulation.java:594)
    at greenfoot.core.Simulation.runOneLoop(Simulation.java:552)
    at greenfoot.core.Simulation.runContent(Simulation.java:215)
    at greenfoot.core.Simulation.run(Simulation.java:205)

**Comment by VictorNorman** [comment]
Could not reproduce.  Tried with this Scratch project: 

https://scratch.mit.edu/projects/118214864/#editor

A clone is created after 1 second.  Then, hit space bar to delete it.

Since you didn't give me a test to reproduce on, I'm sending this back to you...

**Comment by lucentlavender** [comment]
It appears the issue here is when there are multiple 'whenIStartAsAClone' scripts, if the clone is deleted in 1 of the scripts, it will still try to execute the other 'whenIStartAsAClone' script even though the sprite doesn't have access to the world any more. 
[test23.zip](https://github.com/VictorNorman/ScratchFoot/files/430774/test23.zip)
