### ISSUE TITLE
Converting SOMEDAY fails

### ISSUE THREAD

**Issue by VictorNorman** [VictorNorman/ScratchFoot#166]
https://scratch.mit.edu/projects/156829642/

Scheduling Run
Scheduling Run
Scheduling Run
b'Proceesing var: level'
Adding varInfo entry for Level : level --> (level, Int)
No variable definition dictionary found in script json: level
Writing code to /Users/vtn2/research/scratch2greenfoot/summer2017/ScratchFoot/SOMEDAY/Level.java.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/vtn2/anaconda/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
    return self.func(*args)
  File "s2g.py", line 2879, in convertButtonCb
    convert()
  File "s2g.py", line 2675, in convert
    sprite = Sprite(sprData)
  File "s2g.py", line 2307, in __init__
    name = convertToJavaId(sprData['objName'], True, True)
  File "s2g.py", line 176, in convertToJavaId
    if noLeadingNumber and res[0].isdigit():
IndexError: string index out of range

**Comment by lucentlavender** [comment]
The problem here is that one of the sprites is named "!?". This fails to be converted to a valid java id since there are no letters.
