### ISSUE TITLE
Copy constructor is not generated if there is no whenIStartAsAClone block

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#55]
If an object in scratch has no "When I start as a clone" event, when converted it will not have a copy constructor, meaning that attempting to clone it will crash.

**Comment by VictorNorman** [comment]
Can you put the java stack trace into this bug?

**Comment by lucentlavender** [comment]
java.lang.NoSuchMethodException: Apple.<init>(Apple, int, int)
    at java.lang.Class.getConstructor0(Class.java:3082)
    at java.lang.Class.getDeclaredConstructor(Class.java:2178)
    at Scratch.callConstructor(Scratch.java:1034)
    at Scratch.createCloneOf(Scratch.java:1020)
    at Scratch.createCloneOf(Scratch.java:1011)
    at Stage.whenFlagClickedCb1(Stage.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at Scratch$Sequence.run(Scratch.java:240)
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at Scratch$Sequence.run(Scratch.java:240)
Caused by: java.lang.NullPointerException
    at greenfoot.World.addObject(World.java:396)
    at Scratch.createCloneOf(Scratch.java:1024)
    at Scratch.createCloneOf(Scratch.java:1011)
    at Stage.whenFlagClickedCb1(Stage.java:26)
    ... 5 more

**Comment by lucentlavender** [comment]
This needs a change in s2g so that the copy constructor is always generated for every actor, as cloning does not work if an object does not have a copy constructor.
