### ISSUE TITLE
If/else block crashes s2g

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#63]
Traceback (most recent call last):
  File "s2g.py", line 1648, in <module>
    codeObj = genScriptCode(script)
  File "s2g.py", line 1447, in genScriptCode
    whenSpriteCloned(codeObj, script[1:])
  File "s2g.py", line 476, in whenSpriteCloned
    cbStr += block(1, tokens) + "\n"  # add blank line after defn.
  File "s2g.py", line 116, in block
    genIndent(level) + "}\n"
  File "s2g.py", line 127, in stmts
    retStr += stmt(level + 1, aStmt)
  File "s2g.py", line 146, in stmt
    return genCodeFunc(level, tokenList)
  File "s2g.py", line 546, in doForever
    retStr += stmts(level, tokens[1])
  File "s2g.py", line 127, in stmts
    retStr += stmt(level + 1, aStmt)
  File "s2g.py", line 146, in stmt
    return genCodeFunc(level, tokenList)
  File "s2g.py", line 569, in doIfElse
    assert len(tokens) == 4 and tokens[0] == 'doIfElse'

**Comment by VictorNorman** [comment]
Please attach the project.json so i can reproduce this.

Sent on a Sprint Samsung Galaxy S® III

-------- Original message --------
From: jld73
Date:07/13/2016 3:11 PM (GMT-05:00)
To: VictorNorman/ScratchFoot
Subject: [VictorNorman/ScratchFoot] If/else block crashes s2g (#63)

Traceback (most recent call last):
File "s2g.py", line 1648, in
codeObj = genScriptCode(script)
File "s2g.py", line 1447, in genScriptCode
whenSpriteCloned(codeObj, script[1:])
File "s2g.py", line 476, in whenSpriteCloned
cbStr += block(1, tokens) + "\n" # add blank line after defn.
File "s2g.py", line 116, in block
genIndent(level) + "}\n"
File "s2g.py", line 127, in stmts
retStr += stmt(level + 1, aStmt)
File "s2g.py", line 146, in stmt
return genCodeFunc(level, tokenList)
File "s2g.py", line 546, in doForever
retStr += stmts(level, tokens[1])
File "s2g.py", line 127, in stmts
retStr += stmt(level + 1, aStmt)
File "s2g.py", line 146, in stmt
return genCodeFunc(level, tokenList)
File "s2g.py", line 569, in doIfElse
assert len(tokens) == 4 and tokens[0] == 'doIfElse'

##

**Comment by lucentlavender** [comment]
[project.json.zip](https://github.com/VictorNorman/ScratchFoot/files/362328/project.json.zip)
