### ISSUE TITLE
changeSizeBy not implemented in s2g.py

### ISSUE THREAD

**Issue by VictorNorman** [VictorNorman/ScratchFoot#90]
Found this by trying to convert https://scratch.mit.edu/projects/111016761/#editor

**Comment by lucentlavender** [comment]
I cannot reproduce this. When I try to convert it I get an error in glideTo: 
----------- Sprite: Parrot ----------------
Traceback (most recent call last):
  File "s2g.py", line 1772, in <module>
    codeObj = genScriptCode(script)
  File "s2g.py", line 1535, in genScriptCode
    whenIReceive(codeObj, script[0][1], script[1:])
  File "s2g.py", line 546, in whenIReceive
    cbStr += block(1, tokens) + "\n"  # add blank line after defn.
  File "s2g.py", line 118, in block
    genIndent(level) + "}\n"
  File "s2g.py", line 129, in stmts
    retStr += stmt(level + 1, aStmt)
  File "s2g.py", line 148, in stmt
    return genCodeFunc(level, tokenList)
  File "s2g.py", line 557, in doForever
    retStr += stmts(level, tokens[1])
  File "s2g.py", line 129, in stmts
    retStr += stmt(level + 1, aStmt)
  File "s2g.py", line 148, in stmt
    return genCodeFunc(level, tokenList)
  File "s2g.py", line 990, in repeatUntil
    retStr += stmts(level, tokens[2])
  File "s2g.py", line 129, in stmts
    retStr += stmt(level + 1, aStmt)
  File "s2g.py", line 148, in stmt
    return genCodeFunc(level, tokenList)
  File "s2g.py", line 677, in glideTo
    (mathExpr(time), x, y)
TypeError: %d format: a number is required, not list

changeSizeBy seems to be implemented just fine as far as I can tell.
