### ISSUE TITLE
Variable names with spaces, question marks, etc., need to be sanitized

### ISSUE THREAD

**Issue by VictorNorman** [VictorNorman/ScratchFoot#92]
See https://scratch.mit.edu/projects/111016761/#editor for an example.

**Comment by lucentlavender** [comment]
This could be done while typing the variables, if the variable name is not legal, they could presented with an opportunity to enter a new one.

**Comment by VictorNorman** [comment]
When converting  https://scratch.mit.edu/projects/111016761/#editor 
"size counter" becomes sizeCounter, but s2g.py seems to still look for "size counter".

----------- Sprite: Sprite1 ----------------
Traceback (most recent call last):
  File "s2g.py", line 1814, in <module>
    codeObj = genScriptCode(script)
  File "s2g.py", line 1574, in genScriptCode
    whenIReceive(codeObj, script[0][1], script[1:])
  File "s2g.py", line 556, in whenIReceive
    cbStr += block(1, tokens) + "\n"  # add blank line after defn.
  File "s2g.py", line 128, in block
    genIndent(level) + "}\n"
  File "s2g.py", line 139, in stmts
    retStr += stmt(level + 1, aStmt)
  File "s2g.py", line 158, in stmt
    return genCodeFunc(level, tokenList)
  File "s2g.py", line 1001, in repeatUntil
    retStr += stmts(level, tokens[2])
  File "s2g.py", line 139, in stmts
    retStr += stmt(level + 1, aStmt)
  File "s2g.py", line 158, in stmt
    return genCodeFunc(level, tokenList)
  File "s2g.py", line 848, in setVariable
    varType, isGlobal = getTypeAndLocalGlobal(tokens[1])
  File "s2g.py", line 830, in getTypeAndLocalGlobal
    varTok + " unknown.")
ValueError: Sprite Sprite1 variable size counter unknown.
